// ══ STEP 1: Namespace declaration for the Game Store API models.
namespace GameStore.Api.Models;

// ══ STEP 2: Define the Game entity class.
public class Game
{
    // ══ STEP 3: Unique identifier for each game (auto-generated by database).
    public Guid Id { get; set; }

    // ══ STEP 4: Required name of the game.
    public required string Name { get; set; }

    // ══ STEP 5: Navigation property to the associated Genre (nullable).
    // ⚠ Forward-ref: The relationship configuration (foreign key, cascade) will be defined in the DbContext (Phase 3).
    public Genre? Genre { get; set; }

    // ══ STEP 6: Foreign key property linking to the Genre entity.
    public Guid GenreId { get; set; }

    // ══ STEP 7: Price of the game as a decimal value (e.g., 29.99).
    public decimal Price { get; set; }

    // ══ STEP 8: Release date stored as DateOnly (no time component).
    public DateOnly ReleaseDate { get; set; }

    // ══ STEP 9: Required description text for the game.
    public required string Description { get; set; }
}
